"""create files table

Revision ID: a1b2c3d4e5f6
Revises: f62ad80f194f
Create Date: 2025-02-12 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'f62ad80f194f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор файла (UUID)'),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, comment='Оригинальное имя файла при загрузке'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Относительный путь к файлу от корня хранилища'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Размер файла в байтах'),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True, comment='MIME-тип файла'),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True, comment='Расширение файла'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активного файла'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=False)
    op.create_index(op.f('ix_files_original_filename'), 'files', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_original_filename'), table_name='files')
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
